/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE blockBaseService PLEASE EDIT ../block.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Block } from '../../domain/rapi-dev-kit_db/block';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Block.service.ts
 */

/*
 * SCHEMA DB Block
 *
	{
		Actyve: {
			type: 'Boolean',
			required : true
		},
		FontendAPIHook: {
			type: 'String'
		},
		Settings: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		BlockType: {
			type: Schema.ObjectId,
			required : true,
			ref : "Block"
		},
		Privileges: {
			type: Schema.ObjectId,
			ref : "Block"
		},
	}
 *
 */
@Injectable()
export class BlockBaseService {

    contextUrl: string = environment.endpoint + '/blocks';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * BlockService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Block): Observable<Block> {
        return this.http
            .post<Block>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * BlockService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * BlockService.findByActyve
    *   @description CRUD ACTION findByActyve
    *   @param Objectid key Id of the resource Actyve to search
    *
    */
    findByActyve(id: string): Observable<Block[]> {
        return this.http
            .get<Block[]>(this.contextUrl + '/findByActyve/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * BlockService.findByBlockType
    *   @description CRUD ACTION findByBlockType
    *   @param Objectid key Id of the resource BlockType to search
    *
    */
    findByBlockType(id: string): Observable<Block[]> {
        return this.http
            .get<Block[]>(this.contextUrl + '/findByBlockType/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * BlockService.findByFontendAPIHook
    *   @description CRUD ACTION findByFontendAPIHook
    *   @param Objectid key Id of the resource FontendAPIHook to search
    *
    */
    findByFontendAPIHook(id: string): Observable<Block[]> {
        return this.http
            .get<Block[]>(this.contextUrl + '/findByFontendAPIHook/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * BlockService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Block> {
        return this.http
            .get<Block>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * BlockService.getBlockType
    *   @description CRUD ACTION getBlockType
    *   @param Objectid id ID of Block from BlockType
    *
    */
    getBlockType(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'getBlockType')
            .pipe(
                map(response => response)
            );
     }

    /**
    * BlockService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Block[]> {
        return this.http
            .get<Block[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * BlockService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Block): Observable<Block> {
        return this.http
            .post<Block>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
