/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE block-typeBaseService PLEASE EDIT ../block-type.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { BlockType } from '../../domain/rapi-dev-kit_db/block-type';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../BlockType.service.ts
 */

/*
 * SCHEMA DB BlockType
 *
	{
		Code: {
			type: 'String'
		},
		Name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		BlockType: {
			type: Schema.ObjectId,
			required : true,
			ref : "Block"
		},
		ItemType: {
			type: Schema.ObjectId,
			required : true,
			ref : "BlockType"
		},
	}
 *
 */
@Injectable()
export class BlockTypeBaseService {

    contextUrl: string = environment.endpoint + '/blocktypes';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * BlockTypeService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: BlockType): Observable<BlockType> {
        return this.http
            .post<BlockType>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * BlockTypeService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * BlockTypeService.findByName
    *   @description CRUD ACTION findByName
    *   @param Objectid key Id of the resource Name to search
    *
    */
    findByName(id: string): Observable<BlockType[]> {
        return this.http
            .get<BlockType[]>(this.contextUrl + '/findByName/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * BlockTypeService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<BlockType> {
        return this.http
            .get<BlockType>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * BlockTypeService.getItemType
    *   @description CRUD ACTION getItemType
    *   @param Objectid id ID of BlockType from ItemType
    *
    */
    getItemType(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'getItemType')
            .pipe(
                map(response => response)
            );
     }

    /**
    * BlockTypeService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<BlockType[]> {
        return this.http
            .get<BlockType[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * BlockTypeService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: BlockType): Observable<BlockType> {
        return this.http
            .post<BlockType>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
