/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE roleBaseService PLEASE EDIT ../role.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Role } from '../../domain/rapi-dev-kit_db/role';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Role.service.ts
 */

/*
 * SCHEMA DB Role
 *
	{
		Name: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Privileges: {
			type: Schema.ObjectId,
			ref : "Block"
		},
		RolePrivileges: {
			type: Schema.ObjectId,
			ref : "User"
		},
	}
 *
 */
@Injectable()
export class RoleBaseService {

    contextUrl: string = environment.endpoint + '/roles';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * RoleService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Role): Observable<Role> {
        return this.http
            .post<Role>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * RoleService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * RoleService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Role> {
        return this.http
            .get<Role>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * RoleService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Role[]> {
        return this.http
            .get<Role[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * RoleService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Role): Observable<Role> {
        return this.http
            .post<Role>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
