/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE ItemBase PLEASE EDIT ../item.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { User } from '../user';
import { Item } from '../item';
import { ItemType } from '../item-type';

/**
 * This is the model of Item object
 *
 */
export class ItemBase {

    constructor() { }

    public _id: string;
    public Active: Boolean;
    public Created?: number;
    public Data?: string;
    public Modified?: number;
    public Order?: number;
    public Protected?: Boolean;
    public Status?: string;
    // Relations Creator
    public Creator: User | string;
    // Relations Link
    public Link: Item | string;
    // Relations Type
    public Type: ItemType | string;
}
